=== Raptor-Team/incubator-gid/gid.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://f150.oschina.io/raptor-gid/gid"
  xmlns="http://f150.oschina.io/raptor-gid/gid">
  <xs:element name="sequences">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="breadcrumb"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="snowflake"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ticktock"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="breadcrumb">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="incr" type="xs:long"/>
      <xs:attribute name="start" type="xs:long"/>
      <xs:attribute name="cache">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="10000"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="snowflake">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="workerIdWidth">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="10"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="sequenceWidth">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="21"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="ticktock">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="workerIdWidth">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="3"/>
            <xs:maxInclusive value="10"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="sequenceWidth">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="3"/>
            <xs:maxInclusive value="10"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Raptor-Team/incubator-gid/src/test/resources/xml/sequence.xml
<?xml version="1.0" encoding="UTF-8"?>
<sequences xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://f150.oschina.io/raptor-gid/gid"
  xsi:schemaLocation="http://f150.oschina.io/raptor-gid/gid http://f150.oschina.io/raptor-gid/gid.xsd">

  <breadcrumb cache="2" incr="1" name="aid" start="1"/>
  <breadcrumb cache="100" incr="11" name="bid" start="9999"/>
  <breadcrumb cache="0" incr="-1" name="bid" start="9999"/>
  <breadcrumb incr="-1" name="did" start="9999"/>

  <!-- snowflake类型提供64位二进制粗略序、全局唯一、自增长的sequence,此类型不可有incr、start、cache等属性 -->
  <snowflake name="eid"/>
  <snowflake name="eid" sequenceWidth="12" workerIdWidth="10"/>

  <ticktock name="fid" sequenceWidth="3" workerIdWidth="3"/>
</sequences>
